{
 "title": "PV",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Grid out total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\" and r[\"entity_id\"] == \"power_meter_exported\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Grid in total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\" and r[\"entity_id\"] == \"power_meter_consumption\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Inverter state",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"inverter_pv_connection_status\")\r\n  |> last()\r\n  |> toString()"
    }
   ]
  },
  {
   "title": "Solar in",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\" and r[\"entity_id\"] == \"huawei_inverter_power_in\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({_value:r._value, _time: r._time, _field: \"Solar in\"}))"
    }
   ]
  },
  {
   "title": "Grid in / out",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\" and r[\"entity_id\"] == \"power_meter_active_power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({_value:r._value, _time: r._time, _field: \"Grid in / out\"}))"
    }
   ]
  },
  {
   "title": "Battery in / out",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\" and r[\"entity_id\"] == \"battery_charge_discharge_power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({_value:r._value, _time: r._time, _field: \"Battery in / out\"}))"
    }
   ]
  },
  {
   "title": "String 1 current",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\" and r[\"entity_id\"] == \"inverter_pv_1_current\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({_value:r._value, _time: r._time, _field: \"String 1 current\"}))"
    }
   ]
  },
  {
   "title": "String 1 voltage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\" and r[\"entity_id\"] == \"inverter_pv_1_voltage\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({_value:r._value, _time: r._time, _field: \"String 1 voltage\"}))"
    }
   ]
  },
  {
   "title": "Battery capacity",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\" and r[\"entity_id\"] == \"battery_state_of_capacity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({_value:r._value, _time: r._time, _field: \"Capacity\"}))"
    }
   ]
  }
 ]
}